name: admob_ext
description: AdMob extension package
version: 0.0.1
homepage: ""

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  get: ^4.6.5
  google_mobile_ads: ^1.3.0
  flutter_funding_choices: ^0.3.0+2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.